### ISSUE TITLE
New Module checklist

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-validation#3]
### Issue description

- [x] Use [Project template](https://github.com/micronaut-projects/micronaut-project-template) to create a new repository.
- [x] Prefix the repository with `micronaut-`.  
- [x] Add the [project to file sync](https://github.com/micronaut-projects/micronaut-project-template/blob/master/.github/workflows/files-sync.yml#L14) without the `micronaut-` prefix. 
- [x] Add the module to [management](https://github.com/micronaut-projects/management/blob/master/repos.auto.tfvars) repository. 
- [x] Disable Automatic Analysis in the project administration in Sonar Cloud
![Disable Automatic Analysis in the project administration in Sonar Cloud](https://user-images.githubusercontent.com/864788/163421196-2b692f60-2122-43e3-9509-cd53c6d6f455.png)

**Comment by sdelamo** [comment]
I have done the management PR https://github.com/micronaut-projects/management/pull/63

**Comment by sdelamo** [comment]
I have done the sonar part as well.

**Comment by andriy-dmytruk** [comment]
File sync change: https://github.com/micronaut-projects/micronaut-project-template/pull/239
